Update GitHub signature header to use sha256
drone/go-scm pull request #123
Opened 2021-10-05 07:15 UTC by nlecoy

Hi !

First of all, thanks for the work done on Drone.

Just a quick PR to update the header used to validate webhooks from GitHub.
https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github

GitHub still supports `X-Hub-Signature` for backward-compatibility but recommend using the `X-Hub-Signature-256`

2021-10-05 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/drone/go-scm?pullRequest=123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/drone/go-scm?pullRequest=123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/drone/go-scm?pullRequest=123) it.</sub>

2022-01-17 03:15 UTC, bradrydzewski requested changes

2022-01-17 03:15 UTC, bradrydzewski commented on scm/driver/github/webhook.go
> +	sig := req.Header.Get("X-Hub-Signature-256")
We have some folks using this library with older versions of GitHub Enterprise.  In the interest of backward compatibility and ensuring we don't cause any regressions (for our Drone users) I am thinking we should fallback to the original header.

```Go
sig := req.Header.Get("X-Hub-Signature-256")
if sig == "" {
  sig = req.Header.Get("X-Hub-Signature")
}
```

2022-01-17 07:48 UTC, nlecoy commented
Hi there, 

Sorry to comme back to you just now (didn't see first answer). I added your suggestion @bradrydzewski and added some test.

2022-01-23 17:43 UTC, bradrydzewski approved these changes

2022-01-25 15:56 UTC, tphoney commented
Hey @nlecoy thanks for the PR then the additional work. !

2022-01-25 15:56 UTC, merged